# Common settings
common: &common
  adapter : mysql2
  database: enisysmail
  username: enisys
  password: pass
  timeout : 5000
  encoding: utf8
  host: 127.0.0.1

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common

# access_log
jgw_core:
  adapter : mysql2
  database: <%= Rails.env %>_jgw_core
  username: enisys
  password: pass
  encoding: utf8
  reconnect: false
  pool: 5
  host: 127.0.0.1
  socket: /var/lib/mysql/mysql.sock
